-- ==========================================================
-- Schema & Seed Data for table `research_portal`
-- ==========================================================

CREATE TABLE IF NOT EXISTS `research_portal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `section_key` varchar(100) NOT NULL,
  `section_name` varchar(255) NOT NULL,
  `badge_text` varchar(255) DEFAULT NULL,
  `badge_icon` varchar(100) DEFAULT NULL,
  `heading` text DEFAULT NULL,
  `subheading` text DEFAULT NULL,
  `content` longtext DEFAULT NULL,
  `media_url` varchar(255) DEFAULT NULL,
  `extra_data` longtext DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `section_key` (`section_key`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Default seed data (Total: 7 rows)
INSERT IGNORE INTO `research_portal` (`id`, `section_key`, `section_name`, `badge_text`, `badge_icon`, `heading`, `subheading`, `content`, `media_url`, `extra_data`, `status`, `sort_order`, `updated_at`) VALUES
('1', 'hero', 'Hero Banner & Milestones', 'Centre for Advanced Research & Excellence', 'fa fa-flask', 'Research, Innovation & <em>Enterprise</em>', 'Advancing cutting-edge pharmaceutical formulations, commercial product development, student startup incubation, and global indexed publications at Bhabha University Bhopal.', '', '', '{\n    \"breadcrumb_active\": \"Research & Innovation\",\n    \"actions\": [\n        {\n            \"text\": \"Launched Products (15 Aug)\",\n            \"url\": \"#launched-products\",\n            \"icon\": \"fa fa-cube\",\n            \"style\": \"gold\"\n        },\n        {\n            \"text\": \"Patents & Papers\",\n            \"url\": \"#patents-publications\",\n            \"icon\": \"fa fa-database\",\n            \"style\": \"outline\"\n        },\n        {\n            \"text\": \"Incubation Centre\",\n            \"url\": \"#incubation-edc\",\n            \"icon\": \"fa fa-lightbulb-o\",\n            \"style\": \"outline\"\n        }\n    ],\n    \"milestones_title\": \"Research Milestones at a Glance\",\n    \"milestones\": [\n        {\n            \"target\": 250,\n            \"value\": \"250\",\n            \"suffix\": \"+\",\n            \"prefix\": \"\",\n            \"commas\": false,\n            \"label\": \"Patents Filed\"\n        },\n        {\n            \"target\": 1200,\n            \"value\": \"1200\",\n            \"suffix\": \"+\",\n            \"prefix\": \"\",\n            \"commas\": true,\n            \"label\": \"Scopus \\/ UGC Papers\"\n        },\n        {\n            \"target\": \"2.4\",\n            \"value\": \"2.4\",\n            \"suffix\": \" Cr\",\n            \"prefix\": \"\\u20b9\",\n            \"commas\": false,\n            \"label\": \"Active Grants\"\n        },\n        {\n            \"target\": 60,\n            \"value\": \"60\",\n            \"suffix\": \"+\",\n            \"prefix\": \"\",\n            \"commas\": false,\n            \"label\": \"Global & Ind. MoUs\"\n        }\n    ]\n}', '1', '1', '2026-09-25 16:58:17'),
('2', 'pharmacy_labs', 'Bhabha Pharmacy Research Laboratories', 'CENTRE OF EXCELLENCE · R&D FACILITY', 'fa fa-flask', 'Bhabha Pharmacy Research Laboratories', 'Pioneering formulation development, phytochemical research, analytical testing, and commercial health innovations under stringent national regulatory approvals and standardization protocols.', '', '', '{\"certified_badge\":\"Certified Facility\",\"certifications\":[{\"title\":\"FSSAI Approved\",\"subtitle\":\"Food Safety & Standards Authority\",\"icon\":\"fa fa-check-circle\",\"theme\":\"fssai\"},{\"title\":\"MSME Registered\",\"subtitle\":\"Ministry of MSME, Govt. of India\",\"icon\":\"fa fa-certificate\",\"theme\":\"msme\"},{\"title\":\"Gumasta Licensed\",\"subtitle\":\"Municipal Trade Registration\",\"icon\":\"fa fa-shield\",\"theme\":\"gumasta\"},{\"title\":\"GMP Compliant\",\"subtitle\":\"Standardized Testing Labs\",\"icon\":\"fa fa-industry\",\"theme\":\"gmp\"}],\"stats\":[{\"val\":\"3+\",\"lbl\":\"Commercial Products\",\"icon\":\"fa fa-cubes\",\"color\":\"#059669\",\"bg\":\"#ECFDF5\"},{\"val\":\"100%\",\"lbl\":\"Regulatory Compliance\",\"icon\":\"fa fa-shield\",\"color\":\"#2563EB\",\"bg\":\"#EFF6FF\"},{\"val\":\"25+\",\"lbl\":\"Faculty Researchers\",\"icon\":\"fa fa-users\",\"color\":\"#D97706\",\"bg\":\"#FEF3C7\"},{\"val\":\"12+\",\"lbl\":\"Active R&D Projects\",\"icon\":\"fa fa-flask\",\"color\":\"#7C3AED\",\"bg\":\"#F5F3FF\"}]}', '1', '2', '2026-09-09 11:05:40'),
('3', 'launched_products', 'Launched Products (Commercial Innovations)', 'Commercial Innovations', 'fa fa-rocket', 'Products Developed & <em>Launched</em>', 'Formulated and commercially launched by Bhabha Pharmacy Research Laboratories on 15th August, adhering to pharmaceutical purity standards.', '', '', '{\"products\":[{\"name\":\"Dextro Zing (Jeera)\",\"subtitle\":\"Nutraceutical Formulation\",\"desc\":\"Instant energy formulation enriched with digestive cumin (Jeera) extracts and essential electrolytes for rapid rehydration and sustained vitality.\",\"icon\":\"fa fa-coffee\",\"image\":\"\",\"badge_left\":\"15 Aug Launch\",\"badge_right\":\"FSSAI Approved\",\"specs\":[{\"label\":\"Category:\",\"value\":\"Oral Electrolyte & Energy Drink\"},{\"label\":\"Flavour:\",\"value\":\"Natural Refreshing Jeera Extract\"},{\"label\":\"Registration:\",\"value\":\"FSSAI / MSME Approved\"}],\"lab\":\"Bhabha Pharmacy Research Labs\"},{\"name\":\"Bhabha Energy Drink\",\"subtitle\":\"Health & Vitality Drink\",\"desc\":\"Scientifically balanced revitalizing beverage designed with active vitamins, minerals, and revitalizing botanical nutrients.\",\"icon\":\"fa fa-bolt\",\"image\":\"\",\"badge_left\":\"15 Aug Launch\",\"badge_right\":\"FSSAI Approved\",\"specs\":[{\"label\":\"Category:\",\"value\":\"Nutritional Beverage\"},{\"label\":\"Key Nutrients:\",\"value\":\"Vitamin B Complex & Electrolytes\"},{\"label\":\"Testing:\",\"value\":\"Lab Standardized & Verified\"}],\"lab\":\"Bhabha Pharmacy Research Labs\"},{\"name\":\"Pure Aloe Vera Gel\",\"subtitle\":\"Herbal Skincare & Cosmetic\",\"desc\":\"Cold-pressed Aloe barbadensis leaf extract enriched with natural Vitamin E. Hypoallergenic and soothing daily application.\",\"icon\":\"fa fa-leaf\",\"image\":\"\",\"badge_left\":\"15 Aug Launch\",\"badge_right\":\"Herbal Pure\",\"specs\":[{\"label\":\"Formulation:\",\"value\":\"99% Pure Organic Aloe Vera\"},{\"label\":\"Properties:\",\"value\":\"Paraben & Sulphate Free\"},{\"label\":\"Testing:\",\"value\":\"Dermatologically Safe & Approved\"}],\"lab\":\"Bhabha Pharmacy Research Labs\"}]}', '1', '3', '2026-09-09 11:20:13'),
('4', 'incubation_edc', 'Incubation Centre & EDC', 'Startup Ecosystem', 'fa fa-building', 'Incubation Centre & <em>EDC</em>', 'Empowering students and faculty to transform innovative ideas into viable enterprises through mentorship and prototyping facilities.', '', '', '{\"boxes\":[{\"title\":\"University / Industrial Incubation Centre\",\"icon\":\"fa fa-industry\",\"desc\":\"Bridging academia with industry by offering pre-incubation, prototyping lab facilities, intellectual property guidance, and investor access.\",\"bullets\":[\"Comprehensive Prototype Development & Pilot Testing Labs\",\"Seed funding support & government grant proposal guidance\",\"Corporate technology transfer & patent filing assistance\"]},{\"title\":\"Entrepreneurship Development Cell (EDC)\",\"icon\":\"fa fa-line-chart\",\"desc\":\"Cultivating an entrepreneurial mindset across all faculties through bootcamps, business plan competitions, and startup pitch events.\",\"bullets\":[\"Annual Startup Summits, Hackathons & Pitch Competitions\",\"One-on-one mentorship by experienced founders & angel networks\",\"Legal and financial advisory for corporate registration & compliance\"]}]}', '1', '4', '2026-09-09 11:05:40'),
('5', 'research_domains', 'Research Pillars & Academic Framework', 'Academic Framework', 'fa fa-sitemap', 'Research Pillars & <em>Framework</em>', 'Institutional framework governing interdisciplinary research, ethical compliance, and technology transfers.', '', '', '{\"domains\":[{\"title\":\"Research Overview & Mandate\",\"icon\":\"fa fa-compass\",\"url\":\"\"},{\"title\":\"Vision & Mission of Research\",\"icon\":\"fa fa-bullseye\",\"url\":\"\"},{\"title\":\"Collaborations & MoUs\",\"icon\":\"fa fa-handshake-o\",\"url\":\"\"},{\"title\":\"Funded Research Projects\",\"icon\":\"fa fa-tasks\",\"url\":\"\"},{\"title\":\"Patents & Publications\",\"icon\":\"fa fa-certificate\",\"url\":\"\"},{\"title\":\"Faculty Training Programs\",\"icon\":\"fa fa-graduation-cap\",\"url\":\"\"},{\"title\":\"Ethical Committee\",\"icon\":\"fa fa-shield\",\"url\":\"\"},{\"title\":\"Skill Development Programs\",\"icon\":\"fa fa-cogs\",\"url\":\"\"},{\"title\":\"Workshops, Seminars & CDE\",\"icon\":\"fa fa-users\",\"url\":\"\"},{\"title\":\"R&D Videos\",\"icon\":\"fa fa-video-camera\",\"url\":\"\"},{\"title\":\"Transfer of Technology (ToT)\",\"icon\":\"fa fa-exchange\",\"url\":\"\"},{\"title\":\"Research Achievements\",\"icon\":\"fa fa-trophy\",\"url\":\"\"},{\"title\":\"University Research Policy\",\"icon\":\"fa fa-book\",\"url\":\"\"}]}', '1', '5', '2026-09-09 11:05:40'),
('6', 'patents_publications', 'Patents, Publications & Scholarly Records', 'Scholarly Records', 'fa fa-database', 'Patents, Publications & <em>Research Papers</em>', 'Verified repository of filed patents, indexed papers (Scopus, UGC CARE), and authored book chapters.', '', '', '{\"tab1_title\":\"Patent Filing Records\",\"tab1_desc\":\"Official patent applications submitted by university faculty and researchers.\",\"tab1_tag\":\"Format: IPO Indian Patent Office\",\"tab1_empty\":\"Official patent filing data will be updated upon departmental submission.\",\"tab2_title\":\"Research Paper List\",\"tab2_desc\":\"Papers indexed in Scopus, SCIE, UGC Care Group I & II, and PubMed journals.\",\"tab2_tag\":\"Indexed Repository\",\"tab2_empty\":\"Official publications list will be updated upon departmental submission.\",\"tab3_title\":\"Books & Chapters Published\",\"tab3_desc\":\"Authored reference textbooks and chapters published by recognized national and international publishers.\",\"tab3_empty\":\"Official authored books and chapters records will be updated upon departmental submission.\"}', '1', '6', '2026-09-09 11:05:40'),
('7', 'media_publications', 'E-Newsletter, Magazine & Blogs', 'Publications', 'fa fa-bookmark', 'E-Newsletter, Magazine & <em>Blogs</em>', 'Stay updated with quarterly research updates, student magazines, and academic insights.', '', '', '{\"cards\":[{\"title\":\"E-Newsletter\",\"icon\":\"fa fa-envelope-open-o\",\"desc\":\"Quarterly digest featuring campus events, academic milestones, and research discoveries.\",\"btn_text\":\"View Newsletters\",\"btn_url\":\"newsletter.php\",\"btn_icon\":\"fa fa-newspaper-o\"},{\"title\":\"University Magazine\",\"icon\":\"fa fa-book\",\"desc\":\"Annual flagship publication highlighting creative writing and institutional milestones.\",\"btn_text\":\"Read Magazine\",\"btn_url\":\"magazine.php\",\"btn_icon\":\"fa fa-file-pdf-o\"},{\"title\":\"Research & Tech Blog\",\"icon\":\"fa fa-rss\",\"desc\":\"Opinion pieces, case studies, and faculty perspectives on emerging technology and healthcare.\",\"btn_text\":\"Explore Blogs\",\"btn_url\":\"blogs.php\",\"btn_icon\":\"fa fa-pencil-square-o\"}]}', '1', '7', '2026-09-09 11:05:40');
